name: CICD using Maven and Tomcat
on:
  push: # run where there is commit to repo
  workflow_dispatch: # run manually
jobs:
  CICDjob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo on ubuntu server
        uses: actions/checkout@v4
      - name: Install Java and Maven on ubuntu server
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cacde: 'maven'
      - name: Build the code
        run: mvn package
      - name: Connect to lab machine and trigger Jenkins job
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: '3.234.239.26'
          username: 'labuser'
          password: 'Nuvelabs123$'
          port: 22
          script: |
            curl -l -u admin:Root123$ http://localhost:8080/job/deployment-pipeline/build?token=token1

